---
name: goreleaser

on:
  push:
    tags:
      - '*'

permissions:
   contents: write # needed to write releases
   id-token: write # needed for keyless signing

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true
      
      - name: Install cosign  
        uses: sigstore/cosign-installer@v3.8.0

      - name: Install syft
        uses: anchore/sbom-action/download-syft@v0.20.2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
